# Generated by Django 5.0.6 on 2026-09-02 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_identity(apps, schema_editor):
    Comment = apps.get_model('comments', 'Comment')
    for c in Comment.objects.select_related('author').iterator():
        Comment.objects.filter(pk=c.pk).update(
            author_name=c.author.username,
            author_email=c.author.email,
            author_homepage=c.author.homepage or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_author__3265ca_idx',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='', max_length=64, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Latin letters and digits only.')]),
            preserve_default=False,
        ),
        migrations.RunPython(fill_identity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author_name'], name='comments_co_author__c8630d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author_email'], name='comments_co_author__893f9e_idx'),
        ),
    ]
